### ISSUE TITLE
grafana-fritzbox-dashboard.json not working

### ISSUE THREAD

**Issue by DanielHani** [blackw1ng/FritzBox-monitor#5]
Hello, I got this set up so far that data is reaching my influxdb instance.

But now that I'm importing the dashboard to Grafana, data is not shown. On import, it sets the datasource to "Grafana" for every panel filling them with random data when it should be using the templating instead.

Could this be related to the Grafana version I'm using (v8.5.5)? I'm so close to the goal. Maybe you can help me out here! :)

Also, it's nicer when on import it allows you to select the datasource. You could include the following to your json file right after the first opening '{':

   "__inputs": [
    {
      "name": "DS_INFLUXDB_TELEGRAF",
      "label": "influxdb_telegraf",
      "description": "",
      "type": "datasource",
      "pluginId": "influxdb",
      "pluginName": "InfluxDB"
    }
  ],

Then at the bottom of the file replace the datasource with:  "datasource": "${DS_INFLUXDB_TELEGRAF}",

For me, it was always using the wrong instance of influxdb as I got two of them set up which is why I added this bit.

Best Regards

**Comment by blackw1ng** [comment]
Interesting! Thanks for catching this and the suggestion - Pull requests are welcome (so you can get the credit), otherwise i would happily include (sorry for the delay, currently on parental leave)

**Comment by blackw1ng** [comment]
Which version of influxdb are you having? please check [#6 ](https://github.com/blackw1ng/FritzBox-monitor/issues/6), whether that may be it.

**Comment by blackw1ng** [comment]
No feedback, thus closing
